routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/apply/{jobPosting:slug}', \App\Http\Controllers\DisplayApplication::class)->name('application');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/dashboard', \App\Http\Livewire\Dashboard::class)->name('dashboard');

    Route::get('/jobs', \App\Http\Livewire\Jobs\JobIndex::class)->name('job-index');
    Route::get('/jobs/{jobPosting}', \App\Http\Livewire\Jobs\ShowJob::class)->name('jobs.show');

    Route::get('/candidates', \App\Http\Livewire\Candidates::class)->name('candidates');

    Route::get('/settings', '\App\Http\Controllers\SettingsController@index')->name('settings');
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

app/View/Components/WidgetLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WidgetLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.widget');
    }
}

resources/views/application.blade.php
<x-widget-layout>
    <form-component />
</x-widget-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <h1 class="sr-only">Profile</h1>
    <!-- Main 3 column grid -->
    <div class="grid grid-cols-1 gap-4 items-start lg:grid-cols-3 lg:gap-8">
        <!-- Left column -->
        <div class="grid grid-cols-1 gap-4 lg:col-span-2">
            <!-- Jobs panel -->
            <section aria-labelledby="profile-overview-title">
                <div class="rounded-lg bg-white overflow-hidden shadow">
                    <h2 class="sr-only" id="profile-overview-title">Profile Overview</h2>
                    <div class="bg-white p-6">
                        <div class="sm:flex sm:items-center sm:justify-between">
                            <div class="sm:flex sm:space-x-5">
                                <div class="flex-shrink-0">
                                    <img class="mx-auto h-20 w-20 rounded-full"
                                        src="{{ Auth::user()->profilePhotoUrl }}"
                                        alt="{{ Auth::user()->name }}">
                                </div>
                                <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
                                    <p class="text-sm font-medium text-gray-600">Welcome back,</p>
                                    <p class="text-xl font-bold text-gray-900 sm:text-2xl">{{ Auth::user()->name }}</p>
                                    <p class="text-sm font-medium text-gray-600">{{ Auth::user()->role }}</p>
                                </div>
                            </div>
                            <div class="mt-5 flex justify-center sm:mt-0">
                                <a href="#"
                                    class="flex justify-center items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
                                    View profile
                                </a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="border-t border-gray-200 bg-gray-50 grid grid-cols-1 divide-y divide-gray-200 sm:grid-cols-3 sm:divide-y-0 sm:divide-x">

                        <div class="px-6 py-5 text-sm font-medium text-center">
                            <span class="text-gray-900">12</span>
                            <span class="text-gray-600">Vacation days left</span>
                        </div>

                        <div class="px-6 py-5 text-sm font-medium text-center">
                            <span class="text-gray-900">4</span>
                            <span class="text-gray-600">Sick days left</span>
                        </div>

                        <div class="px-6 py-5 text-sm font-medium text-center">
                            <span class="text-gray-900">2</span>
                            <span class="text-gray-600">Personal days left</span>
                        </div>

                    </div>
                </div>
            </section>

            <!-- Actions panel -->
            <section aria-labelledby="quick-links-title">
                <div class="bg-white overflow-hidden rounded-lg sm:shadow">
                    @livewire('jobs.job-list')
                </div>
            </section>
        </div>

        <!-- Right column -->
        <div class="grid grid-cols-1 gap-4">
            <!-- Create job posting form -->
            <section aria-labelledby="create-job-posting-form-title">
                <div class="rounded-lg bg-white overflow-hidden shadow">
                    <div class="p-6">
                        @livewire('jobs.create-job-form')
                    </div>
                </div>
            </section>
        </div>
    </div>
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/settings.blade.php
<x-app-layout>
    @livewire('settings.subscription')
    <x-jet-section-border />
    @livewire('settings.payment-method')
    <x-jet-section-border />
    @livewire('settings.upcoming-payment')
    <x-jet-section-border />
    @livewire('settings.invoices')
    <x-jet-section-border />
    @livewire('settings.domains')
</x-app-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>